{% set version = "1.11.0" %}

package:
  name: numpy
  version: {{ version }}

source:
  fn: numpy-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/n/numpy/numpy-{{ version }}.tar.gz
  md5: bc56fb9fc2895aa4961802ffbdb31d0b

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - cython
    - blas * openblas

  run:
    - python
    - blas * openblas

about:
  home: https://www.numpy.org
  license: BSD 3-Clause

extra:
  recipe-maintainers:
    - jakirkham
    - msarahan
